# Generated by Django 4.1.1 on 2022-09-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Posts'},
        ),
    ]
