# Generated by Django 4.1.1 on 2022-09-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
